[package]
name = "mazes"
version = "0.2.0"
authors = ["Blake Winton <bwinton@latte.ca>"]
edition = "2018"


[dependencies]
array-init = "1.0.0"
derive_more = "0.99.11"
enumset = "1.0.4"
itertools = "0.10.0"
lazy_static = "1.4.0"
macroquad = "0.3.0-alpha.14"
quote = "1.0.8"
syn = "1.0.60"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = "3.0.0-beta.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-jsutils = "0.1.4"

[lib]
name = "maze_utils"
proc-macro = true
