[package]
name = "mazes"
version = "0.2.0"
authors = ["Blake Winton <bwinton@latte.ca>"]
edition = "2018"


[dependencies]
array-init = "2.0.1"
derive_more = "0.99.17"
enumset = "1.0.11"
itertools = "0.10.3"
lazy_static = "1.4.0"
macroquad = "0.3.23"
quote = "1.0.21"
syn = "1.0.99"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = {version = "3.2.16", features = ["cargo"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-jsutils = "0.1.5"

[lib]
name = "maze_utils"
proc-macro = true
