name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add wasm
      run: rustup target add wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v2
      with:
        # An explicit cache key that is stable across jobs.
        shared-key: ""
        key: ""
        env-vars: ""
        workspaces: ""
        # Determines if the cache should be saved even when the workflow has failed.
        cache-on-failure: ""
        
    - name: Build
      run: cargo build --verbose --release --target=wasm32-unknown-unknown

    - name: Make directory
      run: mkdir -p target/deploy

    - name: Copy build files
      run: cp target/wasm32-unknown-unknown/release/mazes.wasm target/deploy

    - name: Copy static files
      run: cp static/* target/deploy
 
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/deploy
